apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-maintenance-deployment
spec:
  selector:
    matchLabels:
      app: nginx-maintenance
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-maintenance
    spec:
      containers:
      - name: nginx-maintenance
        image: nginx-maintenance/tainguyenbp
        ports:
        - containerPort: 8081
        imagePullPolicy: Never
