apiVersion: v1
kind: Service
metadata:
  name: nginx-maintenance-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: nginx-maintenance
