name: build nginx maintenance website

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: build project maintenance
    runs-on: self-hosted
    steps:

    - name: Delete container for maintenance old
      run: sudo docker rm -f nginx_mode_maintenance
      
    - name: Delete repo maintenance clone
      run: rm -rf `pwd`/nginx-maintenance
      
    - name: Delete repo maintenance built
      run: sudo rm -rf $HOME/nginx-maintenance   

    - name: Clone project maintenance
      run: git clone https://github.com/tainguyenbp/nginx-maintenance.git

    - name: Check path projec maintenance new
      run: ls -ahl

    - name: Copy repo clone to home directory
      run: sudo scp -r nginx-maintenance $HOME/

    - name: Check path projec maintenance copy
      run: ls -lah
  
    - name: Show path current directory
      run: echo $HOME
          
    - name: build project maintenance new
      run: cd $HOME/nginx-maintenance  && sudo docker-compose up -d --build
    
