name: build nginx maintenance website

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: self-hosted
    steps:

    - name: show hardisk 
      run: df -h
      
    - name: check path current local
      run: pwd

    - name: Delete container for maintenance old
      run: sudo docker rm -f nginx_mode_maintenance

    - name: Delete repo maintenance old
      run: sudo rm -rf nginx-maintenance

    - name: Delete repo maintenance old
      run: sudo rm -rf nginx-maintenance

    - name: Clone project maintenance
      run: git clone https://github.com/tainguyenbp/nginx-maintenance.git

    - name: check path projec maintenance new
      run: ls -ahl
      
    - name: build project maintenance new
      run: cd nginx-maintenance && sudo docker-compose up -d --build
    
