name: build nginx maintenance website

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: self-hosted
    steps:

    - name: show hardisk 
      run: df -h
      
    - name: check path current local
      run: pwd

    - name: check path current local
      run: git clone https://github.com/tainguyenbp/nginx-maintenance.git

    - name: build project nginx
      run: cd nginx-maintenance && dokcer-compose up
    
